### ISSUE TITLE
Could not start SASL ?

### ISSUE THREAD

**Issue by denghp** [BradRuderman/pyhs2#19]
[arrange@localhost pyhs2-master]$ python example.py 
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    database='default') as conn:
  File "/home/arrange/software/pyhs2-master/pyhs2/__init__.py", line 7, in connect
    return Connection(*args, **kwargs)
  File "/home/arrange/software/pyhs2-master/pyhs2/connections.py", line 45, in __init__
    transport.open()
  File "/home/arrange/software/pyhs2-master/pyhs2/cloudera/thrift_sasl.py", line 66, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found

**Comment by Sartner** [comment]
yum -y install cyrus-sasl-plain
and restart hue sloved the problem (in CDH5.4.0)


$ rpm -qa | grep -i cyrus-sasl*
-------------------------------------------
cyrus-sasl-plain-2.1.23-15.el6_6.2.x86_64
cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64
cyrus-sasl-2.1.23-15.el6_6.2.x86_64
cyrus-sasl-devel-2.1.23-15.el6_6.2.x86_64

**Comment by lunkaleung** [comment]
I got the same errors while using Ubuntu 14.04.1 and I have installed the following packages in Ubuntu 14.04.1
-------------------
sasl2-bin
libsasl2-2
libsasl2-dev

Can anyone help?

**Comment by yizizuixia** [comment]
no help windows how solve
