### ISSUE TITLE
Looking for new owner

### ISSUE THREAD

**Issue by BradRuderman** [BradRuderman/pyhs2#47]
Hi All-
My company recently migrated off hive, so I don't think I have the time to maintain this library anymore. Is there anyone who wants to take ownership? Let me know and I can grant access. There is a lot to be done:
- Review Pull Requests
- Update to PEP standards
- Python 3 compatibility
- Include dependencies
- Test for memory leaks + processing large sets.

Thanks!
Brad

**Comment by BradRuderman** [comment]
@smoriarty21 Has offered to take over! Thank you!!!! @smoriarty21

**Comment by smoriarty21** [comment]
Thank you for starting the project!
